version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
  
  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      DB_ROOT_PASSWORD: root
      DB_USERNAME: root
      DB_NAME: test
      DB_PORT: 3306
      DB_HOST: mysql  # localhost
      DB_SYNCHRONIZE: true
    ports:
      - 3000:3000
    depends_on:
      - mysql

  frontend:
    image: frontend:latest
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8000:8000
